services:
  rust-workspace:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: missing
    image: rust-workspace-image:latest
    container_name: rust-workspace-container
    volumes:
      - ./workspace:/root/workspace
    tty: true
    stdin_open: true
    userns_mode: keep-id
    user: root
